require 'chefspec'

describe 'iptables-persistent::default' do
  let(:chef_run) { ChefSpec::ChefRunner.new.converge 'iptables-persistent::default' }
  
  it "installs iptables and iptables-persistent" do
    expect(chef_run).to install_package 'iptables'
    expect(chef_run).to install_package 'iptables-persistent'
  end
  
  it "creates an init script" do
    expect(chef_run).to create_file_with_content "/etc/init.d/iptables-persistent", "### BEGIN INIT INFO"
  end
  
  it "creates ipv4 rules" do
    expect(chef_run).to create_file_with_content "/etc/iptables/rules", "# Generated by iptables-save - example file"
  end
  
  it "creates ipv6 rules" do
    expect(chef_run).to create_file_with_content "/etc/iptables/rules.v6", "# Generated by ip6tables-save - example file"
  end
  
  it "enables and starts iptables-persistent" do
    expect(chef_run).to start_service "iptables-persistent"
    expect(chef_run).to set_service_to_start_on_boot "iptables-persistent"
  end
end

